prepare to systemd highstate compatible
rbkmoney/salt-common pull request #130
Opened 2020-07-16 14:15 UTC by alexminder

2020-11-23 15:28 UTC, niku64 requested changes

2020-11-23 15:28 UTC, niku64 commented on sls/gentoo/makeconf.sls
> -  'set DISTDIR \'"/var/tmp/distfiles"\'',
Такие изменения по умолчанию делать опасно, сломает много хостов в разных окружениях, что собирают пакеты или монтируют отдельный раздел в `/var/tmp`, остальные оставит с мусором в `/var/tmp`. Я понимаю логику разделения cache и tmp, но лучше добавить условие с `pillar`.

2020-11-23 15:28 UTC, niku64 commented on sls/gentoo/core.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
Вылетит с ошибкой, т.к. грейна нет и включена опция не отдавать пустую строку по умолчанию. Лучше использовать `salt.grains.get('elibc', glibc') == 'glibc'`, `include` туда же убрать.

2020-11-23 15:28 UTC, niku64 commented on sls/gentoo/profile.sls
> +        gentoo:default/linux/amd64/17.0/musl/hardened/selinux
17.1 здесь пора прописать.

2020-11-23 15:28 UTC, niku64 commented on sls/lib/glibc.sls
> +{% if salt['grains.get']('elibc')|default('glibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/lib/gnutls.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/lib/nettle.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/lm_sensors/init.sls
> +{% if salt['grains.get']('init') != 'systemd' %}
Здесь тоже лучше прописать через вариант по умолчанию.

2020-11-23 15:28 UTC, niku64 commented on sls/unbound/init.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/unbound/pkg.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/util/arch.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/util/core.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/util/curl.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/util/mailutils.sls
> +  pkg.latest{% if salt['grains.get']('elibc') != 'musl' %}:
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/util/net.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/util/shell.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
И здесь `salt.grains.get('elibc', glibc') == 'glibc'` будет правильней.

2020-11-23 15:28 UTC, niku64 commented on sls/watchdog/init.sls
> +{% if salt['grains.get']('init') != 'systemd' %}
Так же лучше переписать через вариант по умолчанию, конфигурацию watchdog под systemd тоже менять нужно.

2020-11-23 15:28 UTC, niku64 commented on sls/openrc/cronjob.sls
> +{% if salt['grains.get']('init') != 'systemd' %}
Как-то некрасиво выглядит в каждый файл по openrc лепить `if` на `G@init:systemd`.

2020-11-23 15:45 UTC, AydarN approved these changes

2020-11-23 15:58 UTC, alexminder commented on sls/gentoo/profile.sls
> +        gentoo:default/linux/amd64/17.0/musl/hardened/selinux
17.1 для musl не существует

2020-11-23 15:59 UTC, alexminder commented on sls/gentoo/core.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
grain соответствующий есть в модулях. Уже используется.

2020-11-23 16:00 UTC, alexminder commented on sls/util/shell.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
см.выше

2020-11-23 16:10 UTC, alexminder commented on sls/watchdog/init.sls
> +{% if salt['grains.get']('init') != 'systemd' %}
лучше переписать 
не согласен. см. комменатрии выше.

> лучше переписать 

Кому лучше? И каков критерий "лучшести"?

2020-11-23 16:11 UTC, alexminder commented on sls/gentoo/makeconf.sls
> -  'set DISTDIR \'"/var/tmp/distfiles"\'',
Собираются пакеты у нас 2 хостах. Там не будет проблем, ибо я сам проконтроллирую.
И данная директория у нас нигде не монтируется. Если ошибаюсь - покажи где

2020-11-23 16:15 UTC, alexminder commented on sls/openrc/cronjob.sls
> +{% if salt['grains.get']('init') != 'systemd' %}
Соглашусь. Но более интересным вариантом будет переписывание всего хозяйства и вынесением openrc.
Но при текущем построении и дергании не openrc в разных стейтах, а его дочерних частей быстрее сделать как есть.

2020-11-23 16:16 UTC, alexminder commented on sls/lib/glibc.sls
> +{% if salt['grains.get']('elibc')|default('glibc') != 'musl' %}
см. другой коммент

2020-11-23 16:16 UTC, alexminder commented on sls/lib/gnutls.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
см. другой коммент

2020-11-23 16:16 UTC, alexminder commented on sls/lib/nettle.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
см. другой коммент

2020-11-23 16:16 UTC, alexminder commented on sls/lm_sensors/init.sls
> +{% if salt['grains.get']('init') != 'systemd' %}
см. другой коммент

2020-11-23 16:16 UTC, alexminder commented on sls/unbound/pkg.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
см. другой коммент

2020-11-23 16:17 UTC, alexminder commented on sls/util/arch.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
см. другой коммент

2020-11-23 16:17 UTC, alexminder commented on sls/util/core.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
см. другой коммент

2020-11-23 16:17 UTC, alexminder commented on sls/util/curl.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
см. другой коммент

2020-11-23 16:17 UTC, alexminder commented on sls/unbound/init.sls
> +{% if salt['grains.get']('elibc') != 'musl' %}
см. другой коммент

2020-11-25 12:42 UTC, niku64 approved these changes

2020-11-25 13:11 UTC, AydarN approved these changes

2020-12-01 12:10 UTC, merged